resources:
  - name: demo-repo
    type: git
    source:
      uri:
      branch: master

jobs:
  - name: run-unit-test
    plan:
      - get: demo-repo
        trigger: true
      - task: run-unit
        file: demo-repo/ci/task-unit.yml